author: Mike Slinn
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  profile: false
  startings: [html, head, body]
domain: bogus.jekylldemo.com
email: bogus@jekylldemo.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
ignore_theme_config: true
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
make_archive:
  -
    archive_name: demo.zip
    delete: true  # This is the default, and need not be specified.
    files: [ index.html, ~/.ssh/config, /etc/passwd, '!date' ]
  -
    archive_name: demo.tar
    delete: false  # Do not overwrite the archive if it already exists
    files: [ index.html, ~/.ssh/config, /etc/passwd, '!date' ]
plugin_loggers:
  PluginMetaLogger: info
  CleanHook: warn
  DocumentHooks: warn
  DraftFilter: debug
  MyBlock: warn
  PageHooks: warn
  PostHooks: warn
  SiteHooks: warn
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugins: # Use file name of the plugin entry point, not the gem name
  - jekyll_plugin_logger
  - html-proofer
  - jekyll
sass:
  style: compressed
title: Jekyll From/To/Until Plugin Demo
url: https://bogus.jekylldemo.com
